CREATE TABLE IF NOT EXISTS users(
    id SERIAL PRIMARY KEY,
    username VARCHAR(32) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS decks(
    id SERIAL PRIMARY KEY,
    user_id SERIAL REFERENCES users(id),
    name VARCHAR(50) NOT NULL,
    cards JSON NOT NULL DEFAULT '[]'
);